"""Initial migration

Revision ID: 3e4104da4a1c
Revises: 
Create Date: 2025-05-14 20:15:19.787505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4104da4a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_showcases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_prompt', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_rating', sa.Integer(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_showcases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('video_rating')
        batch_op.drop_column('video_prompt')
        batch_op.drop_column('post_rating')

    # ### end Alembic commands ###
