"""Description of changes

Revision ID: e79d7de65fbb
Revises: 3e4104da4a1c
Create Date: 2025-05-14 22:03:18.316998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79d7de65fbb'
down_revision = '3e4104da4a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_showcases', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('product_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('product_org_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('product_nonbg_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('background_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('product_slogan',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('caption_generated',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('final_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_showcases', schema=None) as batch_op:
        batch_op.alter_column('final_image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('caption_generated',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('product_slogan',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('background_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('product_nonbg_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('product_org_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('product_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
